projects_stats.settings:
  type: config_object
  label: 'Projects Stats settings'
  mapping:
    send_stats_to_slack:
      type: boolean
      label: 'Send downloads count to a Slack channel'
    machine_names:
      type: text
      label: 'Project machine names'
    webhook_url:
      type: string
      label: 'Webhook URL'
    sending_type:
      type: string
      label: 'Sending type'
    external_cron_url:
      type: string
      label: 'External cron url'

block.settings.projects_stats:
  type: block_settings
  label: 'Projects Stats settings'
  mapping:
    display_type:
      type: string
      label: 'Display type'
    machine_names:
      type: text
      label: 'Project machine names'
    description:
      type: text
      label: 'Description'
    additional_columns:
      type: sequence
      label: 'Additional columns'
      sequence:
        type: string
    show_downloads:
      type: boolean
      label: 'Show download count'
    collapsible_list:
      type: boolean
      label: 'Make list collapsible'
    sort_by:
      type: string
      label: 'Sort by'
    cache_age:
      type: string
      label: 'Block cache age'
    classes:
      type: string
      label: 'Table/list classes'
    target:
      type: boolean
      label: 'Open project links in the new tab'

